# Generated by Django 2.1.1 on 2018-09-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_mkdocs',
            field=models.BooleanField(
                default=False,
                help_text='the user can use MkDocs site.',
                verbose_name='MkDocs User'),
        ),
    ]
